wallets.create:
  path: /wallets
  controller: App\UI\API\Wallet\CreateWalletAction
  methods: [POST]

wallets.update:
  path: /wallets/{id}
  controller: App\UI\API\Wallet\UpdateWalletAction
  methods: [PUT]

wallets.delete:
  path: /wallets/{id}
  controller: App\UI\API\Wallet\DeleteWalletAction
  methods: [DELETE]

wallets.all:
  path: /wallets
  controller: App\UI\API\Wallet\GetAllWalletsAction
  methods: [GET]

wallets.one:
  path: /wallets/{id}
  controller: App\UI\API\Wallet\GetOneWalletByIdAction
  methods: [GET]
