App\Application\Wallet\Create\CreateWalletCommand:
  properties:
    name:
      - Sequentially:
        - NotBlank:
            message: 'Name is required'
        - Length:
            min: 2
            max: 240
            minMessage: 'Name must be at least {{ limit }} characters long'
            maxMessage: 'Name cannot be longer than {{ limit }} characters'
    startBalance:
      - PositiveOrZero: ~
    currency:
      - Currency: ~

App\Application\Wallet\Update\UpdateWalletCommand:
  properties:
    id:
      - Uuid: ~
    name:
      - Sequentially:
          - NotBlank:
              message: 'Name is required'
          - Length:
              min: 2
              max: 240
              minMessage: 'Name must be at least {{ limit }} characters long'
              maxMessage: 'Name cannot be longer than {{ limit }} characters'
    startBalance:
      - PositiveOrZero: ~
    currency:
      - Currency: ~

App\Application\Wallet\Delete\DeleteWalletCommand:
  properties:
    id:
      - Uuid: ~

App\Application\Category\Create\CreateCategoryCommand:
  properties:
    type:
      - Sequentially:
          - NotBlank:
              message: 'Type is required'
          - Choice:
              choices: [expense, income]
              message: 'Type is invalid'
    name:
      - Sequentially:
          - NotBlank:
              message: 'Name is required'
          - Length:
              min: 2
              max: 240
              minMessage: 'Name must be at least {{ limit }} characters long'
              maxMessage: 'Name cannot be longer than {{ limit }} characters'
    icon:
      - NotBlank:
          message: 'Icon is required'

App\Application\Category\Update\UpdateCategoryCommand:
  properties:
    id:
      - Uuid: ~
    type:
      - Sequentially:
          - NotBlank:
              message: 'Type is required'
          - Choice:
              choices: [expense, income]
              message: 'Type is invalid'
    name:
      - Sequentially:
          - NotBlank:
              message: 'Name is required'
          - Length:
              min: 2
              max: 240
              minMessage: 'Name must be at least {{ limit }} characters long'
              maxMessage: 'Name cannot be longer than {{ limit }} characters'
    icon:
      - NotBlank:
          message: 'Icon is required'

App\Application\Category\Delete\DeleteCategoryCommand:
  properties:
    id:
      - Uuid: ~

App\Application\Transaction\Create\CreateTransactionCommand:
  properties:
    type:
      - Sequentially:
          - NotBlank:
              message: 'Type is required'
          - Choice:
              choices: [expense, income, transfer]
              message: 'Type is invalid'
    sourceWalletId:
      - Sequentially:
          - NotBlank:
              message: 'Source wallet ID is required'
          - Uuid: ~
    targetWalletId:
      - When:
          expression: "value != null"
          constraints:
            - Uuid: ~
    categoryId:
      - When:
          expression: "value != null"
          constraints:
            - Uuid: ~
    date:
      - Date: ~
    description:
      - NotBlank:
          message: 'Description is required'
    amount:
      - Positive: ~

App\Application\Transaction\Update\UpdateTransactionCommand:
  properties:
    id:
      - Uuid: ~
    type:
      - Sequentially:
          - NotBlank:
              message: 'Type is required'
          - Choice:
              choices: [expense, income, transfer]
              message: 'Type is invalid'
    sourceWalletId:
      - Sequentially:
          - NotBlank:
              message: 'Source wallet ID is required'
          - Uuid: ~
    targetWalletId:
      - When:
          expression: "value != null"
          constraints:
            - Uuid: ~
    categoryId:
      - When:
          expression: "value != null"
          constraints:
            - Uuid: ~
    date:
      - Date: ~
    description:
      - NotBlank:
          message: 'Description is required'
    amount:
      - Positive: ~

App\Application\Transaction\Delete\DeleteTransactionCommand:
  properties:
    id:
      - Uuid: ~
