parameters:

services:
    _defaults:
        bind:
            $jwtSecretKey: '%env(resolve:JWT_SECRET_KEY)%'
            $jwtAlgorithm: '%env(resolve:JWT_ALGORITHM)%'
        autowire: true
        autoconfigure: true
    _instanceof:
        App\SharedKernel\Messenger\CommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: command.bus}

        App\SharedKernel\Messenger\QueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: query.bus}

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
